### ISSUE TITLE
Can't connect properly to ESP32

### ISSUE THREAD

**Issue by vegarov** [albertskog/iot-workshop-plant-monitoring#1]
Have followed all the steps in the README.txt file. Everything is ok until i'm connecting the board. then this code show up in the console: 

>>> Connecting to COM3...
:0x3 (DOWN�%==Q�UART0/UART1/SDIO_REI_REO_V2))
waiting for download

I can't get it to continue. Am i doing anything wrong?

**Comment by albertskog** [comment]
I'm not sure about the error message, but it looks like there might be a problem with the Micropython firmware. Can you try re-installing it using the steps shown here?

http://micropython.org/download#esp32

I used strandad firmware esp32-20190529-v1.11.bin

**Comment by albertskog** [comment]
Hi @vegarov, did you get any further? I'll assume the issue is fixed since I did not hear back, let me know if you still have problems! I have some spare boards if you need a replacement.

**Comment by vegarov** [comment]
I've had a lot to do the last month, so I haven't got much time looking at it. I tried to do as proposed in the last reply, but the console can't seem to find the board. Here is the output from cmd:

![2019-11-18_20-06-02](https://user-images.githubusercontent.com/56227137/69081755-f6051600-0a3e-11ea-9a0b-a5574619a3ae.png)

I'm not very familiar with coding in cmd, so it is very possible that I do something wrong.. Any suggestions what to try next?

**Comment by albertskog** [comment]
Seems like you did everything right! I did some searching and found this forum thread:
https://forum.micropython.org/viewtopic.php?t=5382

It looks like this could be a problem with the button labeled "Boot", my guess is that it is connected to GPIO0 as described in the forum thread.

You could try pressing it a few times in case it is stuck in the down position. If that does not help, you could try to remove it - either with a soldering iron if you have access to one, or just break it off with pliers. Either way I can give you a new board, just contact me on `mail [at] albertskog [dot] se`
