### ISSUE TITLE
can not upload new code

### ISSUE THREAD

**Issue by UtaBrandt** [albertskog/iot-workshop-plant-monitoring#2]

**Comment by albertskog** [comment]
Hi Uta, I see you removed the description and closed the issue, did you find a solution yourself?

**Comment by UtaBrandt** [comment]
Yes, I updated the device with a new SSID and want to work a bit more with it. And I forgot a few things since the workshop 😊 But I fixed it at the end.
It seems that the device use much power. Do you have a hint how to optimize the power consumption?
I was also wondering if there is any documentation of the board available, like schematics. I could not find any.

Med vennlig hilsen

Uta Brandt

Instrumentengineer
Teamleader "Sensors, instruments and equipment"
-----------------------------------------------------------------------------------------------------------------
NIVA, Gaustadalléen 21, NO-0349 OSLO
Mob.: + 47 98215395

**Comment by albertskog** [comment]
I think the wifi uses most of the power so to reduce it you could leave wifi off by default, save samples for a period of time, then start the wifi, post the data and then turn wifi off again. Of course this will add some latency, but low power is always a tradeoff..

There is also a way to put the ESP32 to sleep if you want to save even more power between sensor measurements. Have a look here: https://docs.micropython.org/en/latest/library/machine.html?highlight=sleep#machine.lightsleep

I have not found any schematic unfortunately. I have sent a message to DIY More asking if they can share it. Here is the product page if you want to try contacting them yourself: https://www.aliexpress.com/item/32860958750.html
